### ISSUE TITLE
请问线条的事件，需要怎么增加吗？

### ISSUE THREAD

**Issue by wiwengweng** [Summer-andy/topology-react#4]
我看vue上面的线条，有事件的管理，但是react的版本没有；
![image](https://user-images.githubusercontent.com/1968042/101854721-097ca500-3b9d-11eb-8ec3-56413b72eaa8.png)
![image](https://user-images.githubusercontent.com/1968042/101854753-18635780-3b9d-11eb-8ec8-76996f5fdcbf.png)
请问可以怎么加上吗？？

**Comment by Summer-andy** [comment]
我加一下 ~

**Comment by Summer-andy** [comment]
其实线条的事件和节点的事件代码差不多哈 ~ 只是节点是在canvas.node.events 而线条是在canvas.line.events。

**Comment by wiwengweng** [comment]
厉害了。目前topology在实现上和国内的一些商用产品还差一些。请问你是做这方面产品的吗？

**Comment by Summer-andy** [comment]
我做的是Topology在React中的实践(应用) 。 具体产品的细节是由Topology的开源团队做的哦 ~
