### ISSUE TITLE
配置时的鼠标事件

### ISSUE THREAD

**Issue by hellobq** [Summer-andy/topology-react#5]
同学，你好！

在配置流程图时，能给部件（比如 rect）添加鼠标事件吗？
比如：点击、双击、右键。这样的话，就很方便地给这个部件添加自定义数据了

**Comment by Summer-andy** [comment]
我下一步的计划是支持自定义的UI组件哈, 下次更新顺带着你这个一起更新哈

**Comment by hellobq** [comment]
·
