### ISSUE TITLE
头部箭头设置不生效

### ISSUE THREAD

**Issue by dargon5210** [Summer-andy/topology-react#7]
![55F23D95-315D-4907-B650-FAFF2C9BC742](https://user-images.githubusercontent.com/21213337/104690237-072edd00-573f-11eb-9245-396900b8860a.png)

**Comment by Summer-andy** [comment]
![image](https://user-images.githubusercontent.com/30104912/105329160-cdad1480-5c0b-11eb-9556-dab9d2158515.png)
可以的呀

**Comment by dargon5210** [comment]
可能版本的问题， 我这边安装的应该是最新版的，代码中canvas.data.fromArrowType设置不生效，改成canvas.data.fromArrow就可以了

**Comment by Summer-andy** [comment]
对的 是底层的Core 字段名称改了

**Comment by Summer-andy** [comment]
应该是这个了 https://github.com/le5le-com/topology/issues/152
