### ISSUE TITLE
位置错乱

### ISSUE THREAD

**Issue by hellobq** [Summer-andy/topology-react#8]
点击预览 => 自适应窗口大小，运动的汽车位置偏移（bug）：

![image](https://user-images.githubusercontent.com/29953650/111718751-789d2000-8895-11eb-9dff-37df57e53962.png)

**Comment by Summer-andy** [comment]
这不是bug哈, 因为预览的时候 汽车的位置是动态计算的。你点了自适应窗口大小, 汽车还是按照之前的位置移动, 其他静态物体就不是之前的位置了。

**Comment by Summer-andy** [comment]
![image](https://user-images.githubusercontent.com/30104912/111718984-e9dcd300-8895-11eb-9e0b-b0657fec28f7.png)

**Comment by Summer-andy** [comment]
如果要自适应也支持小车轨迹正常的话, 我们就需要计算出整体的偏移量 然后给小车加上对应的数值即可。

**Comment by Summer-andy** [comment]
已修复



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: hellobq ***@***.***&gt;
发送时间: 2021年3月19日 09:29
收件人: Summer-andy/topology-react ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: 回复：[Summer-andy/topology-react] 位置错乱 (#8)





 
点击预览 =&gt; 自适应窗口大小，运动的汽车位置偏移（bug）：
